[Variables]

Language=English
Location=4PWQ3V58+4PWQ3V58+
Unit=m
Format=H
Hidden=0
Hidden2=1
Player=iTunes

;-------------------------------------------------------------
;-------------------------------------------------------------

;NOTES:

;This below is the settings for the dock with icons.
;If you are not familiar with Rainmeter from earlier,please don't edit anything!
;It's too complicated and sensitive,if you don't know what you doing!
;But i will try to explain to you as much as i can.This "#@#\" is shortened for "@Resources" folder.It's a folder where the icons and other parts of the skin are located.
;If you want to change icon-s,new icon-s,you must put in "@Resources" folder.Also,icons must be in PNG file format.
;When you change "icon and name path",for example if you want to change "My Computer" icon to "CCleaner",it should look like this:
;And please don't ask me how you can extend dock..And please,don't ask me how you can extend dock..I will extend dock on every update,for 2 or more icons..

;This is example for some program:

;Icon1NameAndPath=#@#\CCleaner.png
;Icon1Text=CCleaner
;LocationPath1=!Execute ["C:\Program Files\CCleaner\CCleaner64.exe"]

;This is example for some internet links:

;Icon4NameAndPath=#@#\Twitter.png
;Icon4Text=Twitter
;LocationPath4=!Execute ["https://twitter.com/?lang=en"]

;etc..

;On this site : https://docs.rainmeter.net/manual/getting-started/customizing/
;you can find all information,about customizing some skin.To change color,font,size,etc..
;You can also learn how to make your first skin. :)
;Thank you for your understanding! :)


;----------------------Dock Settings--------------------------
;-------------------------------------------------------------


Icon1NameAndPath=#@#\My Computer.png
Icon1Text=My Computer
LocationPath1=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

Icon2NameAndPath=#@#\My Documents.png
Icon2Text=My Documents
LocationPath2=[Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]

Icon3NameAndPath=#@#\Videos.png
Icon3Text=Video
LocationPath3=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]

Icon4NameAndPath=#@#\Pictures.png
Icon4Text=Pictures
LocationPath4=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]

Icon5NameAndPath=#@#\Music.png
Icon5Text=Music
LocationPath5=[Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]

Icon6NameAndPath=#@#\Downloads.png
Icon6Text=Downloads
LocationPath6=[Shell:::{374DE290-123F-4565-9164-39C4925E467B}]

Icon7NameAndPath=#@#\Google.png
Icon7Text=Google
LocationPath7=!Execute ["https://google.com"]

Icon8NameAndPath=#@#\Facebook.png
Icon8Text=Facebook
LocationPath8=!Execute ["https://facebook.com/"]

Icon9NameAndPath=#@#\Gmail.png
Icon9Text=Gmail
LocationPath9=!Execute ["https://mail.google.com/mail/"]

Icon10NameAndPath=#@#\Deviantart.png
Icon10Text=Deviantart
LocationPath10=!Execute ["https://www.deviantart.com/browse/all/customization/skins/sysmonitor/rainmeter/?order=5"]

