[MeasurePlayer]
Measure=Plugin
Plugin=NowPlaying
PlayerName=#MusicPlayer#
PlayerType=Artist
DisableLeadingZero=1

[MeasureCover]
Measure=Plugin
Plugin=NowPlaying
PlayerName=[MeasurePlayer]
PlayerType=Cover

[MeasureTitle]
Measure=Plugin
Plugin=NowPlaying
PlayerName=[MeasurePlayer]
PlayerType=Title

[MeasureAlbum]
Measure=Plugin
Plugin=NowPlaying
PlayerName=[MeasurePlayer]
PlayerType=Album

[MeasurePosition]
Measure=Plugin
Plugin=NowPlaying
PlayerName=[MeasurePlayer]
PlayerType=Position

[MeasureDuration]
Measure=Plugin
Plugin=NowPlaying
PlayerName=[MeasurePlayer]
PlayerType=Duration
