[Variables]
MP01=shell:Appsfolder\Microsoft.BingWeather_8wekyb3d8bbwe!App
MP02=shell:Appsfolder\Microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.mail
MP03=shell:Appsfolder\Microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.calendar
MP04=shell:Appsfolder\Microsoft.BingNews_8wekyb3d8bbwe!AppexNews
MP05=shell:Appsfolder\Microsoft.WindowsMaps_8wekyb3d8bbwe!App
MP06=https://web.whatsapp.com/
MP07=Firefox.exe
MP08=https://www.deviantart.com/customization/skins/sysmonitor/rainmeter/newest/
MP09=C:\Program Files\HWiNFO64\HWiNFO64.exe
MP10=Explorer.exe
