<Name>Battery</Name><Group>Low Battery</Group><Allow>true</Allow>
<Name>Finish Update</Name><Group>System</Group><Allow>true</Allow>
<Name>Music</Name><Group>New Song</Group><Allow>true</Allow>
<Name>Music</Name><Group>Play/Pause</Group><Allow>true</Allow>
<Name>Reminders</Name><Group>Reminders</Group><Allow>true</Allow>
<Name>System</Name><Group>Scout</Group><Allow>true</Allow>
<Name>System</Name><Group>Settings</Group><Allow>true</Allow>
<Name>System</Name><Group>Update Manager</Group><Allow>true</Allow>
<Name>System</Name><Group>Updates</Group><Allow>true</Allow>
<Name>Timer Widget</Name><Group>Timer Done</Group><Allow>true</Allow>