[Player]
Measure=Plugin
Plugin=SpotifyPlugin
Type=Playing

[TRACK]
Measure=Plugin
Plugin=SpotifyPlugin
Type=TrackName

[ARTIST]
Measure=Plugin
Plugin=SpotifyPlugin
Type=ArtistName

[PROGRESS]
Measure=Plugin
Plugin=SpotifyPlugin
Type=Progress

[ALBUM]
Measure=Plugin
Plugin=SpotifyPlugin
Type=AlbumName

[COVER]
Measure=Plugin
Plugin=SpotifyPlugin.dll
Type=AlbumArt
Res=640
DefaultPath=Resources\Images\Blank.Png
CoverPath=#SKINSPATH#\NXT-OS Data\SpotifyCover.png
