[Variables]

; ---------------------------------------- General

Player=iTunes

Color=255,255,255
Font=Slate for OnePlus

Round=1

; ---------------------------------------- Scale

AScale=1.5
BScale=1
PScale=1.5

; ---------------------------------------- Cover Art

BorderCA=0

; ---------------------------------------- Progress Bar

BorderPG=0
PosColor=30,30,30

; ---------------------------------------- Track Info

Size =20
Align=Center

; ---------------------------------------- Visualizer

Bars=39
BarWidth=25
BarHeight=290
BarSpacing=2

; ---------------------------------------- Circles

PPCircle=1
PRCircle=0
NXCircle=0
