[Variables]

Player=iTunes

Update=1
UpdateDivider=50
Blur=1

Alpha=1.0
AlphaBar=1.0

Color=222,27,27
HideGradientBackground=1
HideLines=0

Image=BarH.png

RMSGain=2.3
RMSAttack=100
RMSDecay=100
PeakGain=1.1
PeakAttack=25
PeakDecay=2500
FFTSize=1024
FFTOverlap=512
FFTAttack=25
FFTDecay=150
FreqMin=40
FreqMax=12000
Sensitivity=35


; Original Values
;RMSGain=2.3
;RMSAttack=100
;RMSDecay=100
;PeakGain=1.1
;PeakAttack=25
;PeakDecay=2500
;FFTSize=1024
;FFTOverlap=512
;FFTAttack=25
;FFTDecay=150
;FreqMin=40
;FreqMax=12000
;Sensitivity=35

