[Variables]
;Date indicator line color
Clr.Hrl=255,255,255,0

;===== Positioning options =====
;Cell Dimensions - The dimensions of the individual string meters.
C.w=24
C.h=24
;Spacers and bumper
;Vertical space between cells
Space.x=16
;Horizontal space between cells
Space.y=4
;Space on left and right of calendar
Bumper.x=60
;Space on top of calendar
Bumper.top=40
;Space on bottom of calendar
Bumper.bottom=0