<Icon>C:\Users\arbuc\OneDrive\Documents\Rainmeter\Skins\NXT-OS\@Resources\DockIcons\Captureol.PNG</Icon><Path>C:\Users\arbuc\Documents\AoD</Path><Text>AoD</Text><Format>2</Format>
<Icon>C:\Users\arbuc\OneDrive\Documents\Rainmeter\Skins\NXT-OS\@Resources\DockIcons\Steam.png</Icon><Path>C:\Users\arbuc\Desktop\DV World.lnk</Path><Text>Starbound</Text><Format>1</Format>
<Icon>C:\Users\arbuc\OneDrive\Documents\Rainmeter\Skins\NXT-OS\@Resources\DockIcons\GitHub.png</Icon><Path>C:\Users\arbuc\Desktop\DV World.lnk</Path><Text>DragonVale World</Text><Format>1</Format>
